boot.o: boot.S multiboot.h x86_desc.h types.h
irq.o: irq.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exception.o: exception.c exception.h lib.h types.h
file_sys.o: file_sys.c file_sys.h types.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c x86_desc.h types.h idt.h exception.h lib.h kb.h irq.h rtc.h \
  i8259.h
kb.o: kb.c kb.h types.h i8259.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h kb.h irq.h exception.h file_sys.h
lib.o: lib.c lib.h types.h
rtc.o: rtc.c rtc.h lib.h types.h kb.h i8259.h irq.h
system_call.o: system_call.c
tests.o: tests.c tests.h x86_desc.h types.h lib.h rtc.h kb.h i8259.h \
  irq.h
